[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
  for = "/app.js"
  [headers.values]
    Access-Control-Allow-Origin = "*"
  for = "/dist/app.js"
  [headers.values]
    Access-Control-Allow-Origin = "*"